name: Course Management CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'CourseManagementService/**'
      - 'CourseManagementService/Dockerfile'
      - 'CourseManagementService/package*.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./CourseManagementService

    - name: Build Docker image
      run: docker build -t binodbandara/coursemanagementservice:${{ github.sha }} .
      working-directory: ./CourseManagementService

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: binodbandara
        password: ${{ secrets.dckr_pat_iUWg0VjoAgkYsOBNeWYZ7p7dV1c }}

    - name: Push Docker image to Docker Hub
      run: docker push binodbandara/coursemanagementservice:${{ github.sha }}
      working-directory: ./CourseManagementService

    # # Add deployment steps here based on your cloud service provider
    # - name: Deploy to Cloud Service
    #   run: |
    #     # Your deployment commands go here
    #     echo "Deployment step is not configured yet"
